## Site title
title: 'Vuekyll'

## Site description
description: 'A Vue theme of Jekyll blog.'

## Site colour (default set 'green')
# Options: green, blue, red, yellow-orange, purple
colour:

## Site author settings
author:
  name: 'Vue'
  url: 'https://sunbossrs.github.io/jekyll-theme-vuekyll/'
  avatar: '/img/avatar.png'
  description: ''

## The base of the site
baseurl: ''

## Language (default set 'en')
# Options: cn, en
lang: ''

## Manager panel
manager:
  use: # true or false
  edit_repo_url: 'https://github.com/sunbossrs/jekyll-theme-vuekyll/edit/master/' # Your open-source platform repo url + /edit/master/

paginate: 5
paginate_path: "/blog/page:num/"

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed

exclude:
  - Gemfile
  - LICENSE.txt
  - README.md

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
