## Site title
#title: Vuedocs

## Site description
description: 'Vue theme for jekyll.'

## The url of this site
url: 'https://sunbossrs.github.io/jekyll-theme-vuedocs'

## The header image of homepage.
heroImage: 'img/heroImage.jpg'

## Site author settings
author:
  name: 'Vue'
  avatar: '/jekyll-theme-vuedocs/img/avatar.svg'
  description: 'I am a student.'

## The base of the site (MUST ADD '/' BEFORE PATHNAME)
baseurl: '/jekyll-theme-vuedocs'

## Navigation bar list
nav:
  'Home': '/'
  'Tags': '/tags'
  'About': '/about'
  'Friends': '/friends'

## Enable or disable comment system (options: true / false)
usecomment: true

## Site comment system option (options: vssue, gitalk, disqus, valine, utterances, livere)
comment: 'vssue'

## Infos for comment system
vssue_platform: 'github' (options: github, gitlab, bitbucket, gitee. NO-REQUIRE-CAPITALIZE)
comment_info: # (something if not required, just keep blank)
  clientid: ''
  clientsecret: '' #vssue_if_not_required_just_keep_blank
  repo: ''
  owner: ''
  disqus_shortname: '' #disqus
  appid: '' #valine
  appkey: '' #valine
  valine_placeholder: '' #valine
  utterances_theme: 'github-light' # (options: github-light, github-black, github-dark-orange, icy-dark, dark-blue, photon-dark)
  utterances_repo: '' # as GithubUsername/repo
  utterances_issue_term: '' # (options: pathname, url, title, og:title)

## Manager panel
manager:
  use: '' # options: true / false
  edit_repo_url: 'https://github.com/xxx/xxx.github.io/edit/master/' # your_opensource_platform_repository_url_in_the_branch_and_edit_mode. / REMEMBER TO ADD '/' AT LAST

## Show how many posts per page
paginate: 5

## The paginate path location
paginate_path: "/page:num/"

## The jekyll plugins option
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
