## Site title
title: 'Vuekyll'

## Site description
description: 'A Vue theme of Jekyll blog.'

## The url of this site
url: 'https://sunbossrs.github.io/jekyll-theme-vuekyll'

## Site colour  (option: green, blue, red, yellow-orange, purple)
colour: green

## Site author settings
author:
  name: 'Vue'
  avatar: '/img/avatar.png'
  description: 'I am a student.'

## The base of the site (P.S. must add '/' at last)
baseurl: 'jekyll-theme-vuekyll/'

## Navigation bar list
nav:
  Home: '/'
  Tags: '/tags'
  About: '/about'
  Friends: '/friends'

## Site comment system option (option: vssue, gitalk, disqus, valine)
comment: vssue

## Infos for comment system
vssue_platform: github # (option: github, gitlab, bitbucket, gitee. NO-REQUIRE-CAPITALIZE)
comment_info:
  clientid: '' 
  clientsecret: '' # (if not requred, keep blank)
  repo: ''
  owner: ''
  disqus_shortname: '' # (keep blank if u r not using disqus)
  appid: '' # (keep blank if u r not using valine)
  appkey: '' # (keep blank if u r not using valine)
  valine_placeholder: '' # (keep blank if u r not using valine)

## Manager panel
manager:
  use: '' # true / false
  edit_repo_url: 'https://github.com/sunbossrs/jekyll-theme-vuekyll/edit/master/' # Your open-source platform repo url + /edit/master/

## Show how many posts per page
paginate: 2

## The paginate path location
paginate_path: "/page:num/"

## The jekyll plugins option
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
