## Site title
title: 'Vuekyll'

## Site description
description: 'A Vue theme of Jekyll blog.'

## The url of this site
url: 'https://sunbossrs.github.io/jekyll-theme-vuekyll'

## Site colour (blank = 'green')
##-- green, blue, red, yellow-orange, purple
colour:

## Site author settings
author:
  name: 'Vue'
  avatar: '/img/avatar.png'
  description: 'I am a student.'

## The base of the site
baseurl: ''

## Language (blank = 'en')
##-- cn, en
lang: ''

## Navigation bar list
nav:
  Home: '/'
  Tags: '/tags'
  About: '/about'
  Friends: '/friends'

## Manager panel
manager:
  use: '' # true / false
  edit_repo_url: 'https://github.com/sunbossrs/jekyll-theme-vuekyll/edit/master/' # Your open-source platform repo url + /edit/master/

paginate: 5

paginate_path: "/blog/page:num/"

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
